version: "3.9"

services:
  mariadb:
    container_name: at03-data
    image: mariadb:10
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - as02
    environment:
      MYSQL_ROOT_PASSWORD: admi@123!
      MYSQL_DATABASE: as02
      MYSQL_USER: as02
      MYSQL_PASSWORD: admi@123!

  nginx:
    container_name: at03-nginx
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    links:
      - mariadb
    ports:
      - 80:80
    networks:
      - as02

volumes:
  db_data: {}

networks:
  as02:
    driver: bridge